name: Security Scan (DIVA)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 15 * * 3' # Every Wednesday

jobs:
  codeql-analysis:
    name: CodeQL (Java + C/C++)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java, cpp

      # Install Android SDK using Java 17
      - name: Setup Java 17 for Android SDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK 23 & Build Tools
        run: |
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          curl -fo sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q sdk.zip -d "$ANDROID_HOME/cmdline-tools"
          mv "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest"
          yes | sdkmanager --licenses
          sdkmanager --install "platforms;android-23" "build-tools;23.0.2"

      # Switch to Java 8 for old Gradle build
      - name: Setup Java 8 for Gradle build
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (Java + JNI)
        run: ./gradlew assembleDebug || true

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  dependency-scan:
    name: Java Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Java 17 for Android SDK install
      - name: Setup Java 17 for Android SDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK 23 & Build Tools
        run: |
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          curl -fo sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q sdk.zip -d "$ANDROID_HOME/cmdline-tools"
          mv "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest"
          yes | sdkmanager --licenses
          sdkmanager --install "platforms;android-23" "build-tools;23.0.2"

      # Switch to Java 8 for Gradle dependency check
      - name: Setup Java 8 for Gradle build
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          base-ref: 'master~1'
          head-ref: 'master'

      - name: Gradle Dependency Check
        run: ./gradlew dependencyCheckAnalyze || true

  secret-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: zricethezav/gitleaks-action@v2
        with:
          fail: true
