name: Security Scan (DIVA)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 15 * * 3' # Every Wednesday

jobs:
  codeql-analysis:
    name: CodeQL (Java + C/C++)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java, cpp

      - name: Setup Java 17 (for sdkmanager)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install NDK
        run: sdkmanager "ndk;21.4.7075529"

      # Switch back to Java 11 for Gradle build
      - name: Setup Java 11 (for Gradle)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (Java + JNI)
        run: ./gradlew assembleDebug

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  dependency-scan:
    name: Java Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          base-ref: 'master~1'
          head-ref: 'master'

      - name: Gradle Dependency Check
        run: ./gradlew dependencyCheckAnalyze || true

  secret-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: zricethezav/gitleaks-action@v2
        with:
          fail: true
