name: Security Scan (DIVA)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 15 * * 3' # Every Wednesday

jobs:
  codeql-analysis:
    name: CodeQL (Java + C/C++)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java, cpp

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Android SDK (Java 11-compatible tools)
        run: |
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          cd "$ANDROID_HOME/cmdline-tools"
          curl -fo sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          mkdir latest
          unzip sdk.zip -d latest
          rm sdk.zip
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
          yes | sdkmanager --licenses
          sdkmanager --install "platforms;android-23" "build-tools;23.0.2" "ndk;21.4.7075529"

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (Java + JNI)
        run: ./gradlew assembleDebug

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  dependency-scan:
    name: Java Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Android SDK (Java 11-compatible tools)
        run: |
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          cd "$ANDROID_HOME/cmdline-tools"
          curl -fo sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          mkdir latest
          unzip sdk.zip -d latest
          rm sdk.zip
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
          yes | sdkmanager --licenses
          sdkmanager --install "platforms;android-23" "build-tools;23.0.2" "ndk;21.4.7075529"

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          base-ref: 'master~1'
          head-ref: 'master'

      - name: Gradle Dependency Check
        run: ./gradlew dependencyCheckAnalyze || true

  secret-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: zricethezav/gitleaks-action@v2
        with:
          fail: true
